// <auto-generated />
namespace LMS_Application.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class henru_will_not_luke_this : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(henru_will_not_luke_this));
        
        string IMigrationMetadata.Id
        {
            get { return "201701171243023_henru_will_not_luke_this"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
