// <auto-generated />
namespace LMS_Application.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class changeToSchoolClassModel_ScheduleModel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changeToSchoolClassModel_ScheduleModel));
        
        string IMigrationMetadata.Id
        {
            get { return "201701072135329_changeToSchoolClassModel_ScheduleModel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
